<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 04/28/2017
 * Time: 03:19 PM
 */

namespace amintado\widgets;
use yii\base\Widget;
class Navbar extends Widget
{

    protected $ViewFile = '@vendor/amintado/yii2-aprico-asset/views/navbar';
    public function init()
    {
        echo $this->render($this->ViewFile);
    }



    public function run()
    {
        echo ' </div></div></nav>';
        parent::run(); // TODO: Change the autogenerated stub
    }
}