<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 04/27/2017
 * Time: 07:37 PM
 */

namespace amintado\widgets;

use frontend\config\components\html;
use function is_array;
use const null;
use SebastianBergmann\Diff\LCS\TimeEfficientImplementation;
use Yii;
use yii\base\Widget;
class SideBar extends Widget
{

    public $name='کارتابل مشاوران';
    public $version='1.0';
    public $SearchBox=[
        'name'=>'search',
        'placeholder'=>'منوی جست و جو',
        'id'=>'search',
        'action'=>''
    ];
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo $this->render('@vendor/amintado/yii2-aprico-asset/views/sidebar',['name'=>$this->name,'version'=>$this->version,'SearchBox'=>$this->SearchBox]);
    }
    public function run()
    {
        echo '</div></div></div></div>';
    }
}