<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 04/28/2017
 * Time: 06:33 PM
 */

namespace amintado\widgets;

use yii\base\Widget;
class Content extends Widget
{


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }



    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}